# Generated by Django 4.1.5 on 2023-02-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('region', models.CharField(choices=[('region1', 'region1'), ('region2', 'region2'), ('region3', 'region3')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='image_8.jpg', upload_to='images')),
                ('lot_area', models.DecimalField(decimal_places=2, max_digits=9)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bed_room', models.IntegerField()),
                ('bath_room', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
