# Generated by Django 4.1.5 on 2023-02-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('Italy', 'Italy'), ('Spain', 'Spain'), ('Croatia', 'Croatia'), ('Montenegro', 'Montenegro'), ('Albania', 'Albania')], max_length=30),
        ),
    ]
