# Generated by Django 4.1.5 on 2023-02-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_year_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='luggage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
