# Generated by Django 4.1.5 on 2023-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_field',
            field=models.URLField(default='DEFAULT LINK'),
        ),
    ]
