# Generated by Django 4.1.5 on 2023-01-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='show',
        ),
    ]
